language: go
cache: go

before_install:
  - set -e
  - go version
  - go env

install:
  - go mod download

script:
  - go build ./...
  - go test -v -race ./...

notifications:
  email:
    on_success: never

# deploy:
#   api_key:
#     secure: "ls/kOsGUyhlz808IWR65/o2HnAgSGzpgxxCuTBo95Fwt5Aza8vuWLYBTyDbsHsZRIvqaTAzOoN/tPYvkTwu6/fzGjft1PaGTwPI4MRXu6nagp8V8ODqoh/CgoJei9+4aWiGp94Mcs2diJHOj7GKYm8qyTih5WD3JvQqSmvkv7dQ2wUeJES0ZMryUC42ezQUEp6hzx3Tlb1z3V8R8Y53HFLsrLGIME+XlA9IFY6SPhG7JGof/i0BaTjSlJe1oflwSJg8oD2salSH5XY7SK0DFIkr/QHVGS55cwNjEUuPZHZ6H/lRTVbk+d2gNHE+4sDi+cmvdzRV6/7gxDbJ/LoMSxwOU8gEZR7EXw9Gjep5ElvyKsSJOXUiobDvdguCUYKN53fER+jWpP+i43t62HCQmyam9eVSGz2oe21NtNoVcxljYdG7jlsntzZE3IofawsEH+z49tWwMMddewdPnP7HmGk3wnCLWOd2GO9JLm/WG+qik/lrpLiFbyuTTq0QQYwjiyPZF43VZSDHYgwYHgby8BzyJX763UMbE7arKnCy+fB4KEP/MwI/Mv6ZKUYOBnMzJeh9XIykbsR9uTjmgNN74XZDRKOZ+8+IWTnXirNHJVvDh1rnJgLp7wNpohu10Y3TwBDv/LWfTW/QDzAO/ZLKlgxhl7nf+/UFa9OaMZhLuFlo="
#   file_glob: true
#   file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
#   on:
#     condition: $TRAVIS_RUST_VERSION = stable
#     tags: true
#   provider: releases
#   skip_cleanup: true
