[package]
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
description = "A program for backing up your GitHub repos."
name = "repo-backup"
version = "0.2.0"

[[bin]]
name = "repo-backup"
path = "src/bin/repo-backup.rs"
doc = false

[dependencies]