[package]
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
description = "A program for backing up your GitHub repos."
name = "repo-backup"
version = "0.2.0"

[[bin]]
doc = false
name = "repo-backup"
path = "src/bin/repo-backup.rs"

[dependencies]
chrono = "0.4.0"
env_logger = "0.5.0-rc.1"
failure = "0.1.1"
failure_derive = "0.1.1"
log = "0.4.0-rc.1"
serde = "1.0.24"
serde_derive = "1.0.24"
shellexpand = "1.0.0"
structopt = "0.1.6"
structopt-derive = "0.1.6"
toml = "0.4.5"
