[package]
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
description = "A program for backing up your GitHub repos."
documentation = "https://docs.rs/repo-backup"
license = "MIT"
name = "repo-backup"
repository = "https://github.com/Michael-F-Bryan/repo-backup"
version = "0.2.1-alpha.0"

[[bin]]
doc = false
name = "repo-backup"
path = "src/bin/repo-backup.rs"

[badges.appveyor]
repository = "Michael-F-Bryan/repo-backup"

[badges.travis-ci]
repository = "Michael-F-Bryan/repo-backup"

[dependencies]
chrono = "0.4.0"
env_logger = "0.5.0-rc.1"
failure = "0.1.1"
failure_derive = "0.1.1"
gitlab = "0.1001.0"
log = "0.4.0-rc.1"
reqwest = "0.8.1"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"
shellexpand = "1.0.0"
structopt = "0.1.6"
structopt-derive = "0.1.6"
toml = "0.4.5"
sec = { version = "0.99.0", features = ["deserialize", "serialize"] }

[patch.crates-io]
sec = { git = "https://github.com/Michael-F-Bryan/sec-rs", branch = "more-impls" }
