[package]
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
description = "A program for backing up your GitHub repos"
name = "github-backup"
version = "0.1.0"

[[bin]]
name = "github-backup"
path = "src/bin/main.rs"

[dependencies]
clap = "2.25.0"
dotenv = "0.10.1"
env_logger = "0.4.3"
error-chain = "0.10.0"
github-rs = "0.5.0"
hyper = "0.11.1"
log = "0.3.8"
rayon = "0.8.2"
serde = "1.0.10"
serde_derive = "1.0.10"
serde_json = "1.0.2"
tempdir = "0.3.5"
