[package]
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
description = "A program for backing up your GitHub and GitLab repos."
documentation = "https://docs.rs/repo-backup"
license = "MIT"
name = "repo-backup"
repository = "https://github.com/Michael-F-Bryan/repo-backup"
version = "0.2.3-alpha.0"
readme = "README.md"

[badges.appveyor]
repository = "Michael-F-Bryan/repo-backup"

[badges.travis-ci]
repository = "Michael-F-Bryan/repo-backup"

[dependencies]
actix = "0.7.5"
slog = "2.4.1"
